os: linux
dist: bionic
language: python
python:
  - "2.7"
install: sudo apt-get install proxychains4
script:
  - echo -e "[ProxyList]\nsocks5 $TIX_PROXY_HOST $TIX_PROXY_CONF" >tix.conf
  - proxychains4 -q -f tix.conf curl google.com
